version: '3'

services:

  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - mongo_devdb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: shop

  mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    links:
      - mongo:mongo

volumes:
  mongo_devdb: